/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalResetCooldownsRouteImport } from './routes/internal.reset-cooldowns'
import { Route as InternalControlRouteImport } from './routes/internal.control'

const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalResetCooldownsRoute = InternalResetCooldownsRouteImport.update({
  id: '/internal/reset-cooldowns',
  path: '/internal/reset-cooldowns',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalControlRoute = InternalControlRouteImport.update({
  id: '/internal/control',
  path: '/internal/control',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/internal/control': typeof InternalControlRoute
  '/internal/reset-cooldowns': typeof InternalResetCooldownsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/internal/control': typeof InternalControlRoute
  '/internal/reset-cooldowns': typeof InternalResetCooldownsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/internal/control': typeof InternalControlRoute
  '/internal/reset-cooldowns': typeof InternalResetCooldownsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/es'
    | '/internal/control'
    | '/internal/reset-cooldowns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/es' | '/internal/control' | '/internal/reset-cooldowns'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/es'
    | '/internal/control'
    | '/internal/reset-cooldowns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  EsRoute: typeof EsRoute
  InternalControlRoute: typeof InternalControlRoute
  InternalResetCooldownsRoute: typeof InternalResetCooldownsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/reset-cooldowns': {
      id: '/internal/reset-cooldowns'
      path: '/internal/reset-cooldowns'
      fullPath: '/internal/reset-cooldowns'
      preLoaderRoute: typeof InternalResetCooldownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/control': {
      id: '/internal/control'
      path: '/internal/control'
      fullPath: '/internal/control'
      preLoaderRoute: typeof InternalControlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  EsRoute: EsRoute,
  InternalControlRoute: InternalControlRoute,
  InternalResetCooldownsRoute: InternalResetCooldownsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
